### ISSUE TITLE
JSON with a list of cities, a centroid, and maybe extents

### ISSUE THREAD

**Issue by michaelappuhn** [driftmap/tile-generator#1]
To discuss and clarify what is needed by the client

**Comment by michaelappuhn** [comment]
@maybemkl @stalgiag - let's discuss what is needed for the cities list

**Comment by stalgiag** [comment]
An early sketch of an ideal json file would be -

```
{ 
  "nyc" : 
  {
    coords: [00, 00],
    name: 'New York, NY, US", 
    extent: [000000, 00000], // or bounds but I ~think~ extent is more useful
    tiles:
    {
    "5": [[9, 11], [18, 14]],
      }
  },
  "atl" : {
  // etc ...
```

But again, not urgent to start adding these other properties. Just probably better to eventually put these city-specific values in a JSON that we can generate instead of keeping 'em hard-coded.

**Comment by stalgiag** [comment]
@maybemkl I see that you removed the 15 and 16 tiles but I realize that there must be a misunderstanding. I need a JSON file with them removed. It doesn't matter if the files exist in the repo. [This still has 15 & 16 tiles.](https://github.com/driftmap/tile-generator/blob/main/data/cities/us_tile_tree.json)

**Comment by maybemkl** [comment]
I added centroid, bbox and name following your proposed structure. Does it work?

**Comment by maybemkl** [comment]
this is pretty much done since extents aren't a priority, so will close the issue and open a new one once / if we want to solve the question of extents here
