### ISSUE TITLE
Create an upload script for server with config variables

### ISSUE THREAD

**Issue by michaelappuhn** [driftmap/tile-generator#11]
So that we don't have to upload gigs worth of data to the repo every time we make a change, let's create a server upload script.

In order to secure it, we should wrap it in environment variables with a config file.

- [x] Sketch out a series of environment variables for tile upload 
- [x] Create sample config file
- [x] Create real config file, with entry in .gitignore
- [x] Create upload script - (makefile, rsync command, node, or something potentially simpler)
- [x] Put tile directory into .gitignore file
- [x] Remove existing tiles from repo — possibly with a rebase to remove it from history

**Comment by maybemkl** [comment]
where are with this @mvmcconnell?

**Comment by mvmcconnell** [comment]
Just checked these off, so we have the upload script working for mass uploading all the tiles generated, in the future we will add single city updates. I can add the tiles to the gitignore and remove them right now from the directory.
